# Inspired from https://github.com/ecmwf/anemoi-datasets
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-yaml # Check YAML files for syntax errors only
    args: [--unsafe, --allow-multiple-documents]
  - id: debug-statements # Check for debugger imports and py37+ breakpoint()
  - id: end-of-file-fixer # Ensure files end in a newline
  - id: trailing-whitespace # Trailing whitespace checker
  - id: no-commit-to-branch # Prevent committing to main / master
  - id: check-added-large-files # Check for large files added to git
  - id: check-merge-conflict # Check for files that contain merge conflict
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 26.1.0
  hooks:
  - id: black
    args: [--line-length=80]
- repo: https://github.com/pycqa/isort
  rev: 8.0.1
  hooks:
  - id: isort
    args:
    - -l 80
    - --force-single-line-imports
    - --profile black
    - --project lingua-loop
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.0
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix, --select=F401]
