from os import environ

from lingua_loop.config import BASE_DIR

TEST_ON = "ON"
TEST_OFF = "OFF"

ENV_UNIT_TEST = "UNIT_TEST"
DEFAULT_ENV_UNIT_TEST = TEST_OFF
environ[ENV_UNIT_TEST] = DEFAULT_ENV_UNIT_TEST

ENV_INTEGRATION_TEST = "INTEGRATION_TEST"
DEFAULT_ENV_INTEGRATION_TEST = TEST_OFF
environ[ENV_INTEGRATION_TEST] = DEFAULT_ENV_INTEGRATION_TEST

IN_MEMORY = ":memory:?cache=shared"
TEST_DIR = "tests"
TEST_DB = "test.db"
TEST_DATABASE_PATH = str(BASE_DIR / TEST_DIR / TEST_DB)
